    uus_mäng = Button(raam, text="Uus mäng")
    uus_mäng.place(x=525, y=200)
    raskusaste_label = Label(raam, text ="Raskusaste:")
    raskusaste_label.place(x=525, y=300)
    raskusaste = Entry(raam, width=2)
    raskusaste.place(x=600, y=300)
    kontrolli = Button(raam, text="Kontrolli")
    kontrolli.place(x=525, y=250)
    var = 0
    abistajad = Checkbutton(raam, text="Abistajad", variable=var)
    abistajad.place(x=525, y=350)
